### ISSUE TITLE
Schema registry ssl config

### ISSUE THREAD

**Issue by gerardq** [OneCricketeer/schema-registry-transfer-smt#30]
Our schema registry servers are ssl secured so the source schema registry should be accessed over https. Is there a way to specify the truststore location?

**Comment by OneCricketeer** [comment]
What configurations do you currently pass into your client settings?

**Comment by gerardq** [comment]
Since the brokers are mTLS secured in my MM2 config I have both ssl.keystore.location, src.ssl.keystore.location and target.ssl.keystore.location, same for the truststores and passwords. I seem to need all of them. My schema registry servers are not secured, just SSL channel encrypted. That channel is signed by our company root CA, whereas the brokers are signed by a cluster specific CA.

**Comment by OneCricketeer** [comment]
So, I don't use a secured registry at work...

@jheinnic Mind taking a look at this?

**Comment by gerardq** [comment]
Thanks, would expect something like this to work:

"transforms": "AvroSchemaTransfer", 
"transforms.AvroSchemaTransfer.type": "cricket.jmoore.kafka.connect.transforms.SchemaRegistryTransfer",
"transforms.AvroSchemaTransfer.src.schema.registry.url": "https://ssl-schema-registry:443",
"transforms.AvroSchemaTransfer.src.schema.registry.ssl.security.protocol": "SSL",
"transforms.AvroSchemaTransfer.src.schema.registry.ssl.truststore.location": "/tmp/blahblah",
"transforms.AvroSchemaTransfer.src.schema.registry.ssl.truststore.password": "blahblah",
"transforms.AvroSchemaTransfer.dest.schema.registry.url": "http://non-ssl-schema-registry:8081",
"transforms.AvroSchemaTransfer.transfer.message.keys": "false"

**Comment by gerardq** [comment]
It seems to work by adding these params to the jvm when starting connect: 

`-Djavax.net.ssl.trustStore=/blahblah -Djavax.net.ssl.trustStorePassword=blahblah`

Which implies it is set per connect instance, not per configuration. This works for us since we have all our kafka clusters on premise inside the corporate network. Could be a problem when working between cloud environments though.

**Comment by OneCricketeer** [comment]
I was going to suggest something like that, but wasn't completely sure. Especially since such settings are generally for the whole JVM, not really an internal, isolated HTTPS client 

Thanks for verifying.

**Comment by alcudiaMV** [comment]
Hi @gerardq ,

Did you find a way to specify the truststore location?
It seems "transforms.AvroSchemaTransfer.src.schema.registry.ssl.truststore.location" doesn't work.

Thanks

NB: thanks @OneCricketeer

**Comment by OneCricketeer** [comment]
The only properties you can set on the client itself are listed here; truststore isn't one of them - https://github.com/confluentinc/schema-registry/blob/master/client/src/main/java/io/confluent/kafka/schemaregistry/client/SchemaRegistryClientConfig.java

And the only properties able to be set, are those listed in the readme 

As pointed out, truststore is often set via JVM system properties, not per HTTP(S) client

**Comment by gerardq** [comment]
Hi,

Check this: https://github.com/confluentinc/schema-registry/issues/943

Somewhere on that page you'll find the following command which sets the JVM options needed for schema registry, which worked for me:

$ SCHEMA_REGISTRY_OPTS="-Djavax.net.ssl.keyStore=/path/to/my/keystore/here -Djavax.net.ssl.trustStore=/path/to/my/truststore/here -Djavax.net.ssl.keyStorePassword=password -Djavax.net.ssl.trustStorePassword=password" kafka-avro-console-producer --broker-list my.broker --topic my.topic --producer.config ~/ssl.config --property value.schema='{"type" : "record", "name" : "Example", "namespace" : "com.example", "fields" : [ {"name" : "uniqueId", "type" : [ "null", "string" ]} ]}' --property schema.registry.url=my.schema.registry
{"uniqueId" : {"string":"1234567"}}
^C
$


Kind regards,
Gerard Quint
