### ISSUE TITLE
Documentation typo?

### ISSUE THREAD

**Issue by oborsha** [OneCricketeer/schema-registry-transfer-smt#32]
Thank you so much for this plugin, we are loving it as it provides much needed functionality for Kafka Connect.

Your README has a section at the bottom labeled "Subject Renaming" but when I read the documentation on the RegexRouter, it appears that this transform is for transforming the Topic name on the message, _not_ the Avro Subject for the schema that applies to the message.  Am I reading your documentation wrong?  Or is this a typo?

Ultimately, we are trying to update the Schema for each message at dest, and thought we would use this feature, but it doesn't appear to do what we thought.

**Comment by OneCricketeer** [comment]
No typo. 

A subject can be renamed if you use the regex router transform before this one. 

In other words, renaming of the subject is out of scope for the purposes for this code.
