### ISSUE TITLE
MirrorMaker 2 stops transfer messages after setting up Schema Registry Transfer

### ISSUE THREAD

**Issue by lushndm** [OneCricketeer/schema-registry-transfer-smt#36]
Hi. Maybe you can give me a hint what could be wrong.

Trying to set up schema transfer with MM2.
The first iteration works successfully. A schema is created in the target registry and the messages in the topic are displayed correctly.
But then replication stops, new messages stop coming to the target cluster.
After disabling SMT schema transfer, message replication starts working again, but as expected without SMT, the consumer tries to deserialize events with the source schema ID without success.

We are on Kafka 2.8/Confluent 6.0 and using MM2 for A->B one-way replication.

The logs show these errors:
```
Caused by: org.apache.kafka.common.errors.SerializationException: Unknown magic byte!
...
Caused by: cricket.jmoore.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Schema 1 not found; error code: 40403
```

Details written here
https://stackoverflow.com/questions/74952744/mirrormaker-2-stops-transfer-messages-after-setting-up-schema-registry-transfer

Thanks

**Comment by OneCricketeer** [comment]
Responded to SO post
